# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Research Software Development Lessons
tagline:          'Building better scientific software'
description:      'A series of modules on best practices for research software development'
url:              https://research-software-development-lessons.github.io/landing-page/

baseurl: https://research-software-development-lessons.github.io/landing-page/

author:
  name:           'Kyle Niemeyer'
  url:            https://niemeyer-research-group.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Research-Software-Development-Lessons/
